# TEMA #1
# TIPOS DE MATRICES

## Matriz Nula
La matriz nula (o matriz cero) es una matriz la cual todos sus elementos son igual a cero (0).

Por lo tanto, según la definición de la matriz nula, esta matriz puede ser de todas las dimensiones posibles mientras todos sus números sean cero.

\begin{bmatrix}    
0 & 0\\
0 & 0
\end{bmatrix}

<br>

\begin{bmatrix}
0 & 0 & 0 \\
0 & 0 & 0 \\
0 & 0 & 0
\end{bmatrix}

<br>

\begin{bmatrix}
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0
\end{bmatrix}


## Matriz de Identidad

Una matriz identidad o unidad de orden n es una matriz cuadrada donde todos sus elementos son ceros (0) menos los elementos de la diagonal principal que son unos (1). En otras palabras, una matriz identidad solo tiene unos (1) en la diagonal principal y todos los demás elementos de la matriz con ceros (0).

Condicion:
Si $a_{ij}$ = 0 , $\forall_{ij} \neq j \ \land $ $a_{ij}$ = 1 , $\forall_{ij} = j$



\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{bmatrix}

<br>

\begin{bmatrix}
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1
\end{bmatrix}

## Matriz Diagonal

En álgebra lineal, una matriz diagonal es una matriz cuyos elementos fuera de la diagonal principal son todos cero; el término usualmente hace referencia a matrices cuadradas.

Condicion:
$a_{ij}$ = 0 , $\forall_{i} \neq j$
\begin{bmatrix}
0 & 0 & 0\\
0 & 2 & 0\\
0 & 0 & 1
\end{bmatrix}

<br>

## Matriz con Triangulo Superior

En álgebra lineal, una matriz triangular es un tipo especial de matriz cuadrada cuyos elementos por encima o por debajo de su diagonal principal o su diagonal secundaria son cero

Condicion:
Si $a_{ij} = 0, \forall_{i} > j $


\begin{bmatrix}
1 & 3 & 2\\
0 & 2 & 4\\
0 & 0 & 1\\
\end{bmatrix}

<br>

## Matriz con Triangulo Inferior

A diferencia del tipo anterior, en este tipo de matriz al menosuno de los elementos que están debajo de la diagonal principal son diferentes a cero y todos los que están por encima de ella son iguales a cero.

Condicion:
Si $a_{ij} = 0, \forall_{i} < j$

\begin{bmatrix}
1 & 0 & 0\\
5 & 7 & 0\\
7 & 6 & 2
\end{bmatrix}

<br>

## Matriz de tipo Simétrica

Una matriz simétrica es una matriz cuadrada y es idéntica a la matriz de después de haber cambiado las filas por columnas y las columnas por filas.

Condicion:
Si $A = A^T$ entonces $A$ seria simétrica

$A=$
$\begin{bmatrix}
1 & 2\\
2 & 7
\end{bmatrix}$


$A^T=$
$\begin{bmatrix}
1 & 2\\
2 & 7
\end {bmatrix}$

<br>

# Matriz de tipo Antisimétrica

Es una matriz cuadrada donde los elementos fuera de la diagonal principal son simétricamente iguales pero los que están por debajo de la diagonal principal llevan un signo negativo.

$A=$
$\begin{bmatrix}
1 & 3 & 5\\
-3 & -1 & 6\\
-5 & -6 & 2
\end {bmatrix}$

$A^T=$
$\begin{bmatrix}
1 & -3 & -5\\
3 & -1 & 6\\
5 & 6 & 2
\end{bmatrix}$

Condicion:
$A \neq A^T$ entonces es antisimétrica

<br>


## Matriz Reducida

Definición: Una matriz $R_{mxn}$ se llama matriz reducida, escalón por filas ssi:

<br>

a) $R$ es reducida.
<br>
b) Toda la fila de $R$ que tiene todos sus elementos ceros (fila nula) está debajo de todas las filas no nulas.
<br>
c) Si las filas 1, 2,...,r son las filas no nulas de $R$, y si el primer elemento no cero de la fila $i$ esta en la columna 
$K_i , i = 1,2,...,r$ entonces $K_1 < K_2 < ... < K_r$.

<br>

$$A → B_1 → B_2 → ... → B → R$$

$A=$
$\begin{bmatrix}
1 & 2 & 3 & 4 & 5\\
2 & 3 & 4 & 5 & 6\\
3 & 4 & 5 & 6 & 7\\
4 & 5 & 6 & 7 & 8
\end{bmatrix}$
$\simeq$
$\begin{bmatrix}
1 & 0 & -1 & -2 & -3\\
0 & 1 & 2 & 3 & 4\\
0 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0
\end{bmatrix}$

<br>
<br>

## Operaciones con matrices
## Tipos de operaciones:
### SUMA

La unión de dos o más matrices solo puede hacerse si dichas matrices tienen la misma dimensión. Cada elemento de las matrices puede sumarse con los elementos que coincidan en posición en diferentes matrices. 

$$A_{mxn} + B_{mxn} = C_{mxn}$$


$A=$
$\begin{bmatrix}
1 & 2 & 3\\
-1 & -2 & 0
\end{bmatrix}$

<br>

$B=$
$\begin{bmatrix}
0 & 1 & -3\\
3 & 2 & 1
\end{bmatrix}$

<br>

$A+B=$
$\begin{bmatrix}
1 & 3 & 0\\
2 & 0 & 1
\end{bmatrix}$

<br>

## Producto de una matriz por un escalar

Es la aplicación que asocia a cada par formado por un número real y una matriz, otra matriz cuyos elementos se obtienen multiplicando el número real por todos los elementos de la matriz.

$C * A_{mn} = D_{mxn}$


$3$
$\begin{bmatrix}
1 & 2 & 3\\
-1 & -2 & 0
\end{bmatrix}$
$=$
$\begin{bmatrix}
3 & 6 & 9\\
-3 & -6 & 0
\end{bmatrix}$

<br>

## Producto de Matrices

Es la operación de composición efectuada entre dos matrices, o bien la multiplicación entre una matriz y un escalar según unas determinadas reglas.

$$A_{mxd} * B_{dxn} = C_{mxn}$$

$\forall{i} = 1,2,3,...,m$

$\forall{j} = 1,2,3,...,d$

$\forall{K} = 1,2,3,...,n$

<br>

$AB = [a_{2j}][b_{jK}] = [c_{iK}]$

Ej:

$A=$
$\begin{bmatrix}
2 & 1 & 5\\
1 & 3 & 2
\end{bmatrix}$

$B=$
$\begin{bmatrix}
3 & 4\\
-1 & 2\\
2 & 1
\end{bmatrix}$

$A$x$B=$
$\begin{bmatrix}
15 & 15\\
4 & 12
\end{bmatrix}$

<br>

## Inversion de Matrices

Sea $A_{n}$ una matriz cuadrada que opera sobre los $R$; si existe una matriz $B_{n}$ cuadrada tal que $AB = BA = I$

A la matriz $B$ se dice que es inversa de $A$ y $A$ es una matriz inversible; por lo que:

$$B=A^{-1}$$

Entonces

$$AA^{-1}=A^{-1}A=I$$

Colorario

$A^{-1}$ es la inversa de $A$ y $A$ es la inversa de $A^{-1}$

Teorema

Si $A$ es inversible entonces $(A^{-1})^{-1}=A$

Teorema

Si $A$ y $B$ son inversibles entonces su producto es inversible y además: $(AB)$ también es inversible y además:
$$(AB)^{-1}=B^{-1}A^{-1}$$

### Demostración

$$(AB)(AB)^{-1}=ABB^{-1}A^{-1}$$
$$=AIA^{-1}$$
$$=AA^{-1}$$
$$=I$$

*Si dos matrices son inversibles, el producto es inversible*

Ej:

$A=$
$\begin{bmatrix}
2 & -1\\
1 & 3
\end{bmatrix}$
$\simeq$
$\begin{bmatrix}
2 & -1 & 1 & 0\\
1 & 3 & 0 & 1
\end{bmatrix}$
$\simeq$
$\begin{bmatrix}
1 & 3 & 0 & 1\\
2 & -1 & 1 & 0
\end{bmatrix}$
$\simeq$
$\begin{bmatrix}
1 & 3 & 0 & 1\\
0 & -7 & 1 & -2
\end{bmatrix}$
$\simeq$
$\begin{bmatrix}
1 & 3 & 0 & 1\\
0 & 1 & -1/7 & 2/7
\end{bmatrix}$
$\simeq$
$\begin{bmatrix}
1 & 0 & 3/7 & 1/7\\
0 & 1 & -1/7 & 2/7
\end{bmatrix}$

*entonces $A$ es inversible*

*Nota:* Si $R \neq I$ no ha inversa

<br>

## Matriz Ortogonal

Se llama ortogonal cuando su inverso es igual a su transposición:

Si $AA^{T} = D$

$A$ es Ortogonal

<br>

## Matriz Ortonormal

Una base ortonormal si los vectores que la forman son perpendiculares entre si y tienen módulo .

Si $AA^{T} = I$

$A$ es Ortonormal

<br>

## Determinantes

El determinante de una función es definida en la siguiente forma:

$$detA \equiv |A|$$

Siendo $A$ una matriz de orden $n^{-1}$ de que se obtiene de la matriz $A$ eliminando la fila $i$ y la columna $j$, a estos determinantes se les llama menores porque son de menor dimensión a la matriz $A$. Los $a_{ij}$ pueden corresponder a elementos de una fila o columna


### Matriz de Orden 2 

$|A|=$
$\begin{bmatrix}
a_{11} & a_{12}\\
a_{21} & a_{22}
\end{bmatrix}$
$= a_{11} a_{22} - a_{21}a_{12} $

### Matriz de Orden 3

$|A_3|=$
$\begin{bmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}\\
a_{31} & a_{32} & a_{33}
\end{bmatrix}$
$=(-1)^{1+1} a_{11}$
$\begin{bmatrix}
a_{22} & a_{23}\\
a_{32} & a_{33}
\end{bmatrix}$
$+ (-1)^{2+1} a_{21}$
$\begin{bmatrix}
a_{12} & a_{13}\\
a_{32} & a_{33}
\end{bmatrix}$
$+ (-1)^{3+1} a_{31}$
$\begin{bmatrix}
a_{12} & a_{13}\\
a_{22} & a_{23}
\end{bmatrix}$

<br>

## Sistemas de ecuaciones

Los sistemas de ecuaciones en matrices son una forma eficiente de resolver conjuntos de ecuaciones lineales. Se representan las incógnitas y los coeficientes en forma de matrices. Por ejemplo, el sistema de ecuaciones lineales:

\begin{cases}
2x+3y=8\\
4x-2y=2
\end{cases}

Se puede representar matricialmente como:

\begin{bmatrix}
2 & 3 & x & 8\\
4 & -2 & y & 2
\end{bmatrix}

<br>

## Factorización LU

La *factorización LU* es un método para descomponer una matriz en el producto de dos matrices: una matriz triangular inferior ($L$) y una matriz triangular superior ($U$).

Ej:

$A=$
$\begin{bmatrix}
2 & 1 & 3\\
4 & 0 & 2\\
1 & 3 & 1
\end{bmatrix}$

La factorización LU de esta matriz implica encontrar dos matrices $L$ y $U$ tal que $A = LU$. La matriz $L$ es triangular inferior con unos en la diagonal principal, y la matriz $U$ es triangular superior.

Después de aplicar el método de factorización LU a la matriz $A$, obtenemos:

$L=$
$\begin{bmatrix}
1 & 0 & 0\\
2 & 1 & 0\\
1/2 & 1 & 1
\end{bmatrix}$

$U=$
$\begin{bmatrix}
2 & 1 & 3\\
0 & -2 & -4\\
0 & 0 & -1
\end{bmatrix}$

**EJEMPLOS DE LA RESOLUCION DE TIPOS DE MATRICES REALIZADO EN CODIGO DE PHYTON**

In [ ]:
#Importar libreria numpy
import numpy as np

#Creando Matrices A y B
A = np.array([[2, 1, 5],[1,3,2],[3,2,2]])
B = np.array([[3, 4],[-1, 2],[2, 1]])
C = np.array([[1, 2, 3],[4, 5, 6],[1,5,3]])

#Suma de las Matrices A y B (se requiere matrices de las mismas dimensiones)
S = A + C
print(S)

#Multiplicación de las Matrices A y B
M = np.dot(A,B)
print(M)

#Inversa de Matrices A y B
A_inv = np.linalg.inv(A)
C_inv = np.linalg.inv(C)
print(A_inv)
print(C_inv)

#Importar librería scipy
import scipy.linalg

#Obtener descomposición LU de matrices A y B
P, L, U = scipy.linalg.lu(A)
P1, L1, U1 = scipy.linalg.lu(B)
print(P,L,U,P1,L1,U1)

#Reducida de las Matrices
import sympy as sym

D=sym.Matrix([[2,1,0],[3,-2,1],[-2,1,1]])
D.rref(pivots=False)

[[3 3 8]
 [5 8 8]
 [4 7 5]]
[[15 15]
 [ 4 12]
 [11 18]]
[[-0.07407407 -0.2962963   0.48148148]
 [-0.14814815  0.40740741 -0.03703704]
 [ 0.25925926  0.03703704 -0.18518519]]
[[-0.83333333  0.5        -0.16666667]
 [-0.33333333  0.          0.33333333]
 [ 0.83333333 -0.16666667 -0.16666667]]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]] [[ 1.          0.          0.        ]
 [ 0.33333333  1.          0.        ]
 [ 0.66666667 -0.14285714  1.        ]] [[3.         2.         2.        ]
 [0.         2.33333333 1.33333333]
 [0.         0.         3.85714286]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] [[ 1.          0.        ]
 [-0.33333333  1.        ]
 [ 0.66666667 -0.5       ]] [[3.         4.        ]
 [0.         3.33333333]]


Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

# TEMA #2
# ESPACIOS VECTORIALES

Un *espacio vectorial* es un conjunto no vacío "$V$" de objetos, llamados "*vectores*", en el que se han definido dos operaciones: la suma y el producto por un escalar "número real" sujetas a los diez axiomas. Los axiomas deben ser válidos para todos los vectores $u$, $v$ y $w$ en "$V$" y todos los escalares $α$ y $β$ reales.

Llamamos $u + v$ a la suma de vectores en $V$, y $αv$ al producto de un número real α por un vector $v ∈ V$.

### Axiomas
Los axiomas mencionados anteriormente son los siguientes:

1. $u+v ∈ V$
2. $u+v=v+u$
3. $(u+v)+w=u+(v+w)$
4. Existe un vector nulo $0_{V} ∈ V$ tal que $v+0_{V}=v$
5. Para cada $v$ en $V$, existe un opuesto $(-v) ∈ V$ tal que $v+(-v)=0_{V}$
6. $αv ∈ V$
7. $α(u+v)=αu+αv$
8. $(α+β)v=αv+βv$
9. $α(βv)=(αβ)v$
10. $1v=v$
 
### Propiedades

1. $0_{u}=0_{V}$
2. $α0_{V}=0_{V}$
3. $(-α)u=-(αu)$
→ En particular, para $α=1:(-1)u=-u$
4. $αu=0_{V} ⟹ α=0$  ó  $u=0_{V}$

<br>

## Subespacios vectoriales

Sea $V$ un espacio vectorial y $W$ un subconjunto no vacío de $V$.
$W$ es un subespacio de $V$ si $W$ es en sí mismo un espacio vectorial con las mismas operaciones (suma de vectores y producto por un escalar) definidas en $V$.


$W=\{(x_{1},x_{2} ∈ R^{2}: x_{2}=3x_{1}\}$ ¿Es un subespacio vectorial de $R^{2}$?

Primero se analiza el conjunto $W$. Son todos vectores de $R^{2}$ tales que la segunda componente es el triple de la primera:

$$(x_{1},3x_{1})=x_{1}(1,3)$$

$W$ es la recta que pasa por el origen y tiene vector director $(1,3)$, o sea la recta de ecuación $y=3x$

Para decidir si $W$ es un subespacio de $R^{2}$ habría que verificar que se cumplen los axiomas del 1 al 10. En este caso se *cumplen*.

<br>

## Bases y Dimensiones

Conjunto linealmente independiente que a la vez sea un sistema generador de dicho espacio o subespacio.

### Propiedades de las bases

1. Una base es un sistema generador minimal de $S$ (lo más pequeño posible).
2. Es un conjunto independiente maximal dentro de $S$ (lo más grande posible).
3. Una base permite expresar todos los vectores de $S$ como combinación lineal de ella, de manera única para cada vector.

<br>

## Dimensión

Todas las bases de un mismo espacio o subespacio tienen el mismo número de vectores.
Se llama dimensión de dicho espacio o subespacio. 

Por tanto, la dimensión es el máximo número de vectores independientes que podemos
tener en el espacio o subespacio. En otras palabras, es el máximo rango que puede tener un
Es también el rango de cualquier sistema generador de dicho espacio.
conjunto de vectoresde dicho espacio.

### Propiedades de la dimensión

1. Significado físico de la dimensión: los planos tienen dimensión 2, las rectas dimensión 1, el punto dimensión 0. El subespacio $\{0\}$ es el único que tiene dimensión 0.
2. La dimensión de un subespacio en $R^{n}$, coincide con el número de parámetros libres en
su forma paramétrica.
3. Si $S$ y $T$ son subespacios y $S$ está contenido en $T$, entonces $dim S <= dim T$. Además, si se da la igualdad, $dim S = dim T$, ambos espacios han de coincidir.
4. El rango de una familia de vectores, es igual a la dimensión del subespacio que generan.
Es decir: si $v1,v2,. . . v_{n}$ generan un cierto subespacio $S$, y si el rango de dicho conjunto es $r$, entonces $dim S = r$. (Si un cierto conjunto de vectores tienen rango 2, entonces generan un plano; etc.)


# TEMA #3
# ORTOGONALIZACION Y ORTONORMALIZACION

## Proceso de Gram-Schmidt

El proceso de ortogonalización de Gram-Schmidt es un algoritmo para construir, a partir de un conjunto de vectores de un espacio vectorial con producto interno, otro conjunto ortonormal de vectores que genere el mismo subespacio vectorial.

Tambien asegura que dado un conjunto de vectores linealmente independientes en un espacio vectorial real con un producto interior dado, podemos encontrar otros vectores que ahora sean ortonormales, que generen lo mismo y que además «apunten hacia un lado similar» a los vectores originales.

## Interpretacion geometrica

En el espacio euclídeo $R^3$ con el producto escalar usual definido, se propone un método para encontrar un sistema de vectores, perpendiculares entre sí, a partir de tres vectores no coplanarios cualesquiera. Sean $v1$, $v2$, $v3$ de dichos vectores.

El método consiste de dos proyecciones. La base ortogonal de $R^3$ compuesta por $u1$, $u2$, $u3$ se calcula de la siguiente manera.

1.Se escoge arbitrariamente uno de los vectores dados, por ejemplo, $u1$ = $v1$.

2.$u2$ se calcula como la diferencia entre $v2$ y el vector que resulta de proyectar a $v2$ sobe $u1$.

3.$u3$, es la diferencia entre $v3$ y el vector que esulta de proyectar a $v3$ sobre el plano generado por $u1$ y $u2$. La diferencia de vectores tiene como resultado otro vector que es perpendicular al plano. 

Esta sencilla interpretación del algoritmo para un caso que puede verse es susceptible de generalización a espacios vectoriales de dimensión arbitraria, con productos internos definidos, no necesariamente canónicos. Dicha generalización no es otra que el proceso de Gram-Schmidt.

# Ejemplo
1) Determine si los siguientes conjuntos de vectores en $R^n$ es ortogonal, si es ortogonal determine si es también ortonormal y determine si es base para $R^n$

$1) v_1 = \{(2,-4),(2,1)\}$

$2) v_2 = \{(3,2),(-4,-6)\}$

$3) v_3 = \{(4,-1,1),(-1,0,4),(-4,-17,-1)\}$

**RESOLUCION DEL EJEMPLO #1 DE ORTOGONALIZACION Y ORTONORMALIZACION MEDIANTE CODIGO DE PHYTON**

In [ ]:
import numpy as np

#Definiendo vectores v1 y v2
v1=np.array([2,-4])
v2=np.array([2,1])

#Producto punto de los vectores v1 y v2
u=np.dot(v1,v2)
print(u)

#Verificar si es ortonormal (si las magnitudes sale diferente de 1, entonces no es ortonormal)
print(np.linalg.norm(v1))
print(np.linalg.norm(v2))

#Verificar si el conjunto es una base para R^n
M = np.array([v1,v2])
det = np.linalg.det(M)
print(det)

0
4.47213595499958
2.23606797749979
9.999999999999998


# TEMA #4
# CONICAS

El lugar geométrico de los puntos cuya relación de distancias a un punto y una recta fijos es constante recibe el nombre de sección cónica o simplemente cónica.

\begin{cases}
Punto Fijo → Foco\\
Recta Fija → Directriz\\
Relación Constante → Excentricidad (e)
\end{cases}

<br>

*Excentricidad*

$$e=\frac{c}{a}=\frac{\sqrt{a^2+b^2}}{a};e>1$$

<br>

## Categorías de las conicas

Si $e<1$, la cónica se llama *Elipse*

Si $e=1$, la cónica se llama *Parábola*

Si $e>1$, la cónica se llama *Hipérbola*

<br>

## Parábola

### Tipos de ecuación de la parábola

*Foco a la derecha de directriz:*

$$(y-k)^{2}=4a(x-h)$$

*Directriz encima de foco*

$$(x-h)^{2}=-4a(y-k)$$

*Foco a la izquierda de directriz*

$$(y-k)^{2}=-4a(x-h)$$

*Foco encima de directriz*

$$(x-h)^{2}=4a(y-k)$$

<br>

## Elipse

### Ecuación de la elipse

$$\frac{x^2}{a^2} + \frac{y^2}{b^2} = 1$$

Si los focos fueran coordenadas (0,c) y (0,-c), el Eje Mayor estaría sobre el eje $y$ entonces la ec. sería:

$$\frac{x^2}{b^2}+\frac{y^2}{a^2}=1$$

<br>

*Ecuacio de las directrices $D'D'$ y $DD$ respectivamente*

$$x+\frac{a}{e}=0$$y$$x-\frac{a}{e}=0$$

<br>

Se denomina *latus rectum* de la elipse a la cuerda perpendicular al eje mayor por uno de los focos, su longitud es $\frac{2b^{2}}{a}$

<br>

Si el centro de la elipse fuese el punto $(h,k)$ y el eje mayor tiene la dirección del eje $x$, la ecuación de la elipse seria igual a:

$$\frac{(x-h)^2}{a^2}+\frac{(y-k)^2}{b^2}=1$$



$$\frac{(x-h)^2}{b^2}+\frac{(y-k)^2}{a^2}=1$$


<br>

*Ecuacion general de la elipse*

$$Ax^2+By^2+Dx+Ey+F=0$$

<br>

## Hipérbola

### Ecuación de la hipérbola

$$\frac{x^2}{a^2}-\frac{y^2}{b^2}=1$$

$$c^2-a^2=b^2$$

*Los focos tienen coordenadas*

$F(c,0)$ y $F'(-c,0)$

La distancia entre $F$ y $F'$ es igual a $2a$

<br>

*Ecuaciones de las directrices DD'*

$$x=±\frac{a}{e}$$

 Focos están sobre eje $x$

$$y=±\frac{a}{e}$$

 Focos están sobre eje $y$

<br>

*Ecuaciones de las asíntotas*

$$y=±\frac{b}{a}x$$

 Cuando el eje real es $x$

$$y=±\frac{a}{b}x$$

 Cuando el eje real es $y$

<br>

Si el centro de la hipérbola es el pto coordenadas (h,k):

$$\frac{(x-h)^2}{a^2}-\frac{(y-k)^2}{b^2}=1$$

 Eje real paralelo al eje $x$

$$\frac{(y-k)^2}{a^2}-\frac{(y-k)^2}{b^2}=1$$

 Eje real paralelo al eje $y$

<br>

### Manera General de la Ec. de la Hipérbola

$$Ax^2-By^2+Dx+Ey+F=0→$$ siendo $A$ y $B$ del mismo signo.

# TEMA #5
# TRANSFOMACIONES LINEALES Y VECTORES PROPIOS

## Transformaciones Lineales

En primer lugar, una transformación lineal es una función. Por ser función, tiene su dominio y su codominio, con la particularidad de que éstos son espacios vectoriales. Tenemos dos espacios vectoriales $V$ y $W$, y una función que va de $V$ a $W$. O sea una regla de asignación que transforma vectores de $V$ en vectores de $W$. Pero no toda función que transforme vectores de $V$ en vectores de $W$ es una transformación lineal. Debe cumplir ciertas condiciones:

$F: V→W$ es una transformación lineal ssi:

1. $F(u+v)=F(u)+F(v)$ , $ ∀ $ $u,v ∈ V$
2. $F(k,v)=k,F(v)$ , $∀v∈V$ , $∀k∈R$

<br>

### Propiedades de la Transformacion Lineal

*Propiedad #1:*
La imagen del vector nulo del dominio $0_{v}$ es el vector nulo del codominio $0_{w}$:
$$T(0_V)=0_w$$

*Propiedad #2:*
La imagen del vector $-v$ es igual al opuesto de la imagen de $v$:
$$T(-v)=-T(v)$$

*Propiedad #3:*
Consideremos $r$ vectores del espacio vectorial $V$:
$$v_1,v_2,...,v_r ∈ V$$

Se toma una combinación lineal en el dominio:
$$α_1v_1+α_2v_2+α_3v_3+...+α_rv_r$$

En el que $α_i ∈ R$

Si se aplica la transformación lineal $F$ de $V$ a $W$, teniendo en cuenta las propiedades enunciadas en la definición, resulta:

$$F(α_1v_1+α_2v_2+α_3v_3+...+α_rv_r)=α_1F(v_1)+α$$

Es decir que una transformación lineal "transporta" combinaciones lineales de $V$ a $W$, conservando los escalares de la combinación lineal.

$$T(1,0)=(2,1,-1)$$
$$T(0,1)=(1,-1,0)$$

encuentre $T$
$$R^2→R^3$$
$$(x,y)→T(x,y)=?$$

<br>

$$B\{v_1, v_2\} → $$
$B=$
$\begin{cases}
\begin{bmatrix}
1\\
0
\end{bmatrix}
,
\begin{bmatrix}
0\\
1
\end{bmatrix}
\end{cases}$

<br>

$v_1=α_1v_2+α_2v_2$

$v=α$
$\begin{bmatrix}
1\\
0
\end{bmatrix}$
$+α_2$
$\begin{bmatrix}
0\\
1
\end{bmatrix}$

$$x=α_1$$
$$y=α_2$$

$T(\vec{v})=T$
$\left(
    \begin{bmatrix}
    x\\
    y
    \end{bmatrix}
\right)$
$=$
$α_1T$
$\left(
  \begin{bmatrix}
  1\\
  0
  \end{bmatrix}
\right)$
$+α_2T$
$\left(
  \begin{bmatrix}
  0\\
  1
  \end{bmatrix}
\right)$

$T$
$\left(
  \begin{bmatrix}
  x\\
  y
  \end{bmatrix}
\right)$
$=$
$α_1$
$\begin{bmatrix}
2\\
1\\
-1
\end{bmatrix}$
$+α_2$
$\begin{bmatrix}
1\\
-1\\
0
\end{bmatrix}$

$T$
$\left(
  \begin{bmatrix}
  x\\
  y
  \end{bmatrix}
\right)$
$=x$
$\begin{bmatrix}
2\\
1\\
1
\end{bmatrix}$
$+y$
$\begin{bmatrix}
1\\
-1\\
0
\end{bmatrix}$
$=$
$\begin{bmatrix}
2x+4\\
x-y\\
-x
\end{bmatrix}$

<br>

## Vectores Propios

Los vectores pueden visualizarse como flechas de una cierta longitud apuntando en una dirección y sentido determinados.

Los vectores propios de las transformaciones lineales son vectores que, o no son afectados por la transformación o solo resultan multiplicados por un escalar; y, por tanto, no varían su dirección.

Los vectores propios de una matriz simétrica tiene gran importancia en las matemáticas y en la ingeniería, entre los que cabe destacar, el problema de la diagonalización de una matriz, el cálculo de los momentos de inercia y de los ejes principales de inercia de un sólido rígido, o de las frecuencias propias de oscilación de un sistema oscilante.

Formalmente, se definen los vectores propios y valores propios de la siguiente manera:

Sea $A: V→V$ un operador lineal en un cierto K-espacio vectorial $V$ y $V$ en un vector no nulo en $V$. Si existe un escalar tal que:

$Av = cv$

$v/0$, c ∈ K

entonces decimos que $v$ es un vector propio del operador $A$, y su valor propio asociado es $c$. Si $v$ es un vector propio con el valor propio $c$ entonces cualquier múltiplo diferente de cero de $v$ es también un vector propio con el valor propio $c$.  De hecho, todos los vectores propios con el valor propio asociado $c$ junto con 0, forman un subespacio de V, el «espacio propio» para el valor propio $c$. Observe además que un espacio propio $Z$ es un subespacio invariante de $A$, es decir un vector $w$ en $Z$, el vector $Aw$ tambien pertenece a $Z$.

## Valores Propios

La constante h es el valor propio que pertenece al vector propio V.

Los valores propios son las raíces reales (raíces que tienen como solución números reales) que encontramos mediante la ecuación característica.

## Caracteristicas de los valores propios

1.Cada valor propio tiene infinitos vectores propios dado que existen infinitos números reales que pueden formar parte de cada vector propio.

2.Son escalares, pueden ser números complejos (no reales) y pueden ser idénticos (más de un valor propio iguales).

3.Existen tantos valores propios como número de filas (m) o columnas (n) tiene la matriz original.

## Condiciones

Para encontrar vectores y valores propios de una matriz, se debe cumplir: 

1.Matriz $Z$ cuadrada: el número de filas ($m$) es el mismo que el número de columnas ($n$).

2.Matriz $Z$ real. La mayoría de las matrices utilizadas en finanzas tienen raíces reales. ¿Qué ventaja existe en la utilización de raíces reales? Pues que los valores propios de la matriz nunca van a ser números complejos, y eso amigos, nos soluciona mucho la vida.

3.Matriz ($Z-hI$) no invertible: determinante = 0. Esta condición nos ayuda a encontrar siempre vectores propios distintos de cero. Si encontrásemos vectores propios iguales a 0, entonces la multiplicación entre valores y vectores propios sería nula.


\begin{bmatrix}    
3 & -1\\
-2 & 4
\end{bmatrix}

<br>

Al momento de multilplciar los elemetos queda:

$$(3-h)*(4-h)-(-2*-1)=0$$

$$12-3h-4h+h^2-2=0$$

$$h^2-7h+10=0$$


La solución de esta ecuación cuadrática es $h=2$ y $h=5$. Dos valores propios porque el número de filas o columnas de la matriz $Z$ es 2. Entonces, hemos encontrado los valores propios de la matriz $Z$ que a la vez hacen que el determinante sea 0.